//! Drives every golden vector in `vectors.txt` against `PyRandom`.
//!
//! The fixture is committed and generated by `tools/gen-pyrandom-vectors.py`,
//! so this runs with no Python present. Regenerate it if the reference
//! interpreter changes:
//!
//! ```text
//! python3 tools/gen-pyrandom-vectors.py > crates/pahoa-pyrandom/tests/vectors.txt
//! ```

use pahoa_pyrandom::PyRandom;

const VECTORS: &str = include_str!("vectors.txt");

#[derive(Default)]
struct Case {
    name: String,
    seed_str: Option<String>,
    seed_key: Vec<u32>,
    genrand32: Vec<u32>,
    getrandbits: Vec<(u32, Vec<u32>)>,
    randbelow: Vec<(u64, u64)>,
    shuffle: Vec<(usize, Vec<u32>)>,
    state: Vec<u32>,
}

fn parse() -> Vec<Case> {
    let mut cases: Vec<Case> = Vec::new();
    for line in VECTORS.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Seed strings may contain spaces, so split off the keyword only.
        let (kw, rest) = line.split_once(' ').unwrap_or((line, ""));
        match kw {
            "case" => cases.push(Case {
                name: rest.to_string(),
                ..Default::default()
            }),
            "seed_str" => cases.last_mut().unwrap().seed_str = Some(rest.to_string()),
            "seed_key" => cases.last_mut().unwrap().seed_key = nums(rest),
            "genrand32" => cases.last_mut().unwrap().genrand32 = nums(rest),
            "state" => cases.last_mut().unwrap().state = nums(rest),
            "getrandbits" => {
                let (k, words) = rest.split_once(' ').unwrap();
                cases
                    .last_mut()
                    .unwrap()
                    .getrandbits
                    .push((k.parse().unwrap(), nums(words)));
            }
            "randbelow" => {
                let (n, v) = rest.split_once(' ').unwrap();
                cases
                    .last_mut()
                    .unwrap()
                    .randbelow
                    .push((n.parse().unwrap(), v.parse().unwrap()));
            }
            "shuffle" => {
                let (n, perm) = rest.split_once(' ').unwrap();
                cases
                    .last_mut()
                    .unwrap()
                    .shuffle
                    .push((n.parse().unwrap(), nums(perm)));
            }
            other => panic!("unknown keyword {other:?} in vectors.txt"),
        }
    }
    cases
}

fn nums<T: std::str::FromStr>(s: &str) -> Vec<T>
where
    T::Err: std::fmt::Debug,
{
    s.split_whitespace().map(|t| t.parse().unwrap()).collect()
}

/// Builds the generator the way the case specifies. String cases go through the
/// full sha512 derivation; integer cases seed straight from the key, which
/// isolates a derivation bug from an `init_by_array` bug.
fn build(case: &Case) -> PyRandom {
    match &case.seed_str {
        Some(s) => PyRandom::seed_str(s),
        None => PyRandom::seed_key(&case.seed_key),
    }
}

#[test]
fn vectors_file_is_populated() {
    let cases = parse();
    assert!(
        cases.len() >= 10,
        "expected the full vector set, got {}",
        cases.len()
    );
    assert!(cases.iter().any(|c| c.seed_str.is_some()));
    assert!(cases.iter().any(|c| c.seed_str.is_none()));
}

/// The sha512 seed derivation, checked independently of the generator so a
/// failure here localizes the bug immediately.
#[test]
fn seed_derivation_matches_cpython() {
    for case in parse().iter().filter(|c| c.seed_str.is_some()) {
        let s = case.seed_str.as_ref().unwrap();
        let derived = PyRandom::seed_str(s);
        let from_key = PyRandom::seed_key(&case.seed_key);
        assert_eq!(
            derived.to_state(),
            from_key.to_state(),
            "case {}: sha512 seed derivation diverges for {s:?}",
            case.name
        );
    }
}

#[test]
fn genrand32_matches_cpython() {
    for case in parse() {
        let mut r = build(&case);
        for (i, want) in case.genrand32.iter().enumerate() {
            assert_eq!(
                r.getrandbits_u64(32),
                *want as u64,
                "case {}: output {i}",
                case.name
            );
        }
    }
}

#[test]
fn getrandbits_matches_cpython() {
    for case in parse() {
        let mut r = build(&case);
        for (k, want) in &case.getrandbits {
            let got = r.getrandbits_words(*k);
            // CPython trims high-order zero words when building the int, so
            // compare against the shorter of the two with the rest asserted zero.
            let n = want.len().min(got.len());
            assert_eq!(
                &got[..n],
                &want[..n],
                "case {}: getrandbits({k})",
                case.name
            );
            assert!(
                got[n..].iter().all(|&w| w == 0) && want[n..].iter().all(|&w| w == 0),
                "case {}: getrandbits({k}) length mismatch: got {got:?}, want {want:?}",
                case.name
            );
        }
    }
}

#[test]
fn randbelow_matches_cpython() {
    for case in parse() {
        let mut r = build(&case);
        for (n, want) in &case.randbelow {
            assert_eq!(r.randbelow(*n), *want, "case {}: randbelow({n})", case.name);
        }
    }
}

#[test]
fn shuffle_matches_cpython() {
    for case in parse() {
        for (n, want) in &case.shuffle {
            // Each shuffle in the fixture starts from a freshly seeded generator.
            let mut r = build(&case);
            let mut deck: Vec<u32> = (0..*n as u32).collect();
            r.shuffle(&mut deck);
            assert_eq!(&deck, want, "case {}: shuffle({n})", case.name);
        }
    }
}

#[test]
fn state_matches_cpython_and_round_trips() {
    for case in parse() {
        let mut r = build(&case);
        for _ in 0..7 {
            r.getrandbits_u64(32);
        }
        assert_eq!(
            r.to_state().as_slice(),
            case.state.as_slice(),
            "case {}: state after 7 draws",
            case.name
        );

        // Restoring that state must continue the identical sequence, which is
        // what makes a resumed room produce the same hint ordering.
        let mut restored = PyRandom::from_state(&case.state).expect("valid state");
        for i in 0..32 {
            assert_eq!(
                restored.getrandbits_u64(32),
                r.getrandbits_u64(32),
                "case {}: draw {i} after restore",
                case.name
            );
        }
    }
}
