#!/usr/bin/env python3
"""Generate golden vectors for pahoa-pyrandom from CPython's `random`.

pahoa must reproduce CPython's Mersenne Twister bit for bit, because
Archipelago seeds its hint PRNG from the seed name and hint ordering is
therefore reproducible and player-visible. Rather than trust a reading of
`Lib/random.py` and `Modules/_randommodule.c`, we pin the behaviour with
vectors generated from a real interpreter and commit the result, so the Rust
test suite needs no Python at run time.

Usage:
    tools/gen-pyrandom-vectors.py > crates/pahoa-pyrandom/tests/vectors.txt

Format is line-oriented so the Rust side needs no parser dependency:

    # comment
    case <name>
    seed_str <utf8 seed>          -- seed via Random.seed(str); absent for int cases
    seed_key <w0> <w1> ...        -- the little-endian 32-bit key CPython derives
                                     and feeds to init_by_array
    genrand32 <v> <v> ...         -- consecutive 32-bit outputs
    getrandbits <k> <w0> <w1> ... -- one getrandbits(k) call, little-endian words
    randbelow <n> <u64>           -- one _randbelow(n) call
    shuffle <n> <perm ...>        -- shuffle(list(range(n))), resulting order
    state <625 space-separated u32>

Results are emitted as 32-bit word arrays rather than decimal so the Rust side
can verify arbitrary widths without a bignum dependency. `seed_key` is emitted
alongside `seed_str` deliberately: if a case fails, whether the key matches
tells you immediately if the bug is in the sha512 seed derivation or in
init_by_array.
"""

import hashlib
import random
import sys

# Seeds chosen to cover: a plain ASCII name, an Archipelago-style seed name,
# non-ASCII (slot/seed names are user-supplied), empty, and one long enough to
# push the sha512-derived integer well past a single MT key word.
SEED_STRINGS = [
    "TestSeed12345",
    "63459715264743862051",
    "",
    "séed-ñame-✓",
    "x" * 200,
]


def emit(*parts):
    print(" ".join(str(p) for p in parts))


def to_words(n):
    """The little-endian 32-bit words of a non-negative int, as CPython stores them."""
    if n == 0:
        return [0]
    length = (n.bit_length() + 31) // 32
    data = n.to_bytes(length * 4, "little")
    return [int.from_bytes(data[i : i + 4], "little") for i in range(0, len(data), 4)]


def derived_key(seed_value):
    """Reproduce `random_seed` in Modules/_randommodule.c: abs(a) as LE words."""
    if isinstance(seed_value, str):
        b = seed_value.encode()
        seed_value = int.from_bytes(b + hashlib.sha512(b).digest(), "big")
    return to_words(abs(seed_value))


def case(name, seed_kind, seed_value):
    emit("case", name)
    if seed_kind == "str":
        emit("seed_str", seed_value)
    emit("seed_key", *derived_key(seed_value))

    # Raw generator output, the foundation everything else rests on.
    r = random.Random()
    r.seed(seed_value)
    emit("genrand32", *[r.getrandbits(32) for _ in range(16)])

    # getrandbits across the fast path (k <= 32) and the multi-word path,
    # including non-multiples of 32 where the most significant word is shifted
    # down, which is the easiest part to get backwards.
    r = random.Random()
    r.seed(seed_value)
    for k in (1, 2, 7, 8, 31, 32, 33, 53, 64, 65, 100, 128, 257):
        emit("getrandbits", k, *to_words(r.getrandbits(k)))

    # _randbelow drives shuffle; its rejection loop must match exactly or
    # every subsequent draw diverges.
    r = random.Random()
    r.seed(seed_value)
    for n in (1, 2, 3, 5, 7, 10, 16, 17, 100, 1000, 12345, 2**31, 2**53 + 1):
        emit("randbelow", n, r._randbelow(n))

    # Shuffle is what actually orders hints.
    for n in (2, 5, 10, 64, 1000):
        r = random.Random()
        r.seed(seed_value)
        deck = list(range(n))
        r.shuffle(deck)
        emit("shuffle", n, *deck)

    # State must round-trip: saves persist it and a resumed room has to
    # continue the same sequence.
    r = random.Random()
    r.seed(seed_value)
    for _ in range(7):
        r.getrandbits(32)
    version, internal, gauss = r.getstate()
    assert version == 3 and gauss is None and len(internal) == 625, (version, gauss)
    emit("state", *internal)

    print()


def main():
    emit("#", "generated by tools/gen-pyrandom-vectors.py")
    emit("#", "python", sys.version.split()[0])
    print()

    for i, s in enumerate(SEED_STRINGS):
        # Seed strings go through the line format, so anything with a newline
        # or a leading/trailing space would be ambiguous. None of ours are, but
        # assert rather than silently emit a broken vector.
        assert s == s.strip() and "\n" not in s, f"unrepresentable seed {s!r}"
        case(f"str{i}", "str", s)

    # Integer seeding is the path CPython uses internally after the sha512
    # derivation; pinning it separately isolates a bug in init_by_array from a
    # bug in the string derivation.
    for i, n in enumerate([0, 1, 2**32 - 1, 2**32, 2**64 + 12345, 2**615 - 1]):
        case(f"int{i}", "int", n)


if __name__ == "__main__":
    main()
