//! Every server packet type must encode byte-for-byte as Archipelago does.
//!
//! Equivalent JSON is not enough. Key order, the `"class"` tags, compact
//! separators and non-ASCII passthrough are all observable on the wire, and a
//! client that caches or hashes a payload would notice a difference that a
//! semantic comparison would wave through.
//!
//! The reference bytes are committed in `vectors.txt`, generated by
//! `tools/gen-protocol-vectors.py`, so this runs without Python.

use pahoa_proto::server::*;
use pahoa_proto::types::*;
use pahoa_proto::{ServerPacket, encode};
use serde_json::{Map, Value, json};
use std::collections::BTreeMap;

const VECTORS: &str = include_str!("vectors.txt");

fn expected(case: &str) -> &'static str {
    for line in VECTORS.lines() {
        if line.starts_with('#') {
            continue;
        }
        if let Some((name, json)) = line.split_once('\t')
            && name == case
        {
            return json;
        }
    }
    panic!("no vector named {case:?} in vectors.txt");
}

/// Encode a single packet as it appears inside a frame (frames are arrays, so
/// strip the brackets to compare one packet at a time).
fn one(p: ServerPacket) -> String {
    let framed = encode(&[p]);
    framed[1..framed.len() - 1].to_string()
}

#[track_caller]
fn check(case: &str, p: ServerPacket) {
    assert_eq!(one(p), expected(case), "case {case}");
}

fn perms(collect: u8, release: u8, remaining: u8) -> BTreeMap<String, Permission> {
    BTreeMap::from([
        ("collect".to_string(), Permission::from(collect)),
        ("release".to_string(), Permission::from(release)),
        ("remaining".to_string(), Permission::from(remaining)),
    ])
}

#[test]
fn room_info() {
    check(
        "room_info",
        ServerPacket::RoomInfo(RoomInfo {
            version: Version::new(0, 6, 8),
            generator_version: Version::new(0, 6, 4),
            tags: vec!["AP".into()],
            password: true,
            permissions: perms(0, 7, 2),
            hint_cost: 10,
            location_check_points: 1,
            games: vec!["Archipelago".into(), "Timespinner".into()],
            datapackage_checksums: BTreeMap::from([
                ("Archipelago".to_string(), "abc123".to_string()),
                ("Timespinner".to_string(), "def456".to_string()),
            ]),
            seed_name: "12345678901234567890".into(),
            time: 1700000000.5,
        }),
    );
}

#[test]
fn connection_refused() {
    check(
        "connection_refused",
        ServerPacket::ConnectionRefused(ConnectionRefused {
            errors: vec![
                ConnectionRefusedReason::InvalidSlot,
                ConnectionRefusedReason::InvalidPassword,
            ],
        }),
    );
}

#[test]
fn connected() {
    check(
        "connected",
        ServerPacket::Connected(Box::new(Connected {
            team: 0,
            slot: 3,
            players: vec![
                NetworkPlayer {
                    team: 0,
                    slot: 1,
                    alias: "Alice".into(),
                    name: "Alice".into(),
                },
                NetworkPlayer {
                    team: 0,
                    slot: 2,
                    alias: "Bobby".into(),
                    name: "Bob".into(),
                },
            ],
            missing_locations: vec![10, 20, 30],
            checked_locations: vec![1, 2],
            slot_info: BTreeMap::from([
                (
                    "1".to_string(),
                    NetworkSlot {
                        name: "Alice".into(),
                        game: "Timespinner".into(),
                        slot_type: 1,
                        group_members: vec![],
                    },
                ),
                (
                    "2".to_string(),
                    NetworkSlot {
                        name: "Link".into(),
                        game: "Archipelago".into(),
                        slot_type: 2,
                        group_members: vec![1, 3],
                    },
                ),
            ]),
            hint_points: 42,
            slot_data: Some(
                serde_json::value::to_raw_value(&json!({"nested": {"a": [1, 2, 3]}, "flag": true}))
                    .unwrap(),
            ),
        })),
    );
}

#[test]
fn connected_omits_slot_data_entirely_when_not_requested() {
    check(
        "connected_no_slot_data",
        ServerPacket::Connected(Box::new(Connected {
            team: 0,
            slot: 1,
            players: vec![],
            missing_locations: vec![],
            checked_locations: vec![],
            slot_info: BTreeMap::new(),
            hint_points: 0,
            slot_data: None,
        })),
    );
}

#[test]
fn received_items() {
    check(
        "received_items",
        ServerPacket::ReceivedItems(ReceivedItems {
            index: 0,
            items: vec![
                // Start inventory: location -2, player 0.
                NetworkItem {
                    item: 1,
                    location: -2,
                    player: 0,
                    flags: 0,
                },
                NetworkItem {
                    item: 77,
                    location: 1234,
                    player: 2,
                    flags: 0b101,
                },
            ],
        }),
    );
}

#[test]
fn location_info() {
    check(
        "location_info",
        ServerPacket::LocationInfo(LocationInfo {
            locations: vec![NetworkItem {
                item: 5,
                location: 100,
                player: 2,
                flags: 1,
            }],
        }),
    );
}

#[test]
fn room_update_sends_only_what_changed() {
    check(
        "room_update_partial",
        ServerPacket::RoomUpdate(Box::new(RoomUpdate {
            hint_points: Some(12),
            ..Default::default()
        })),
    );
    check(
        "room_update_checked",
        ServerPacket::RoomUpdate(Box::new(RoomUpdate {
            checked_locations: Some(vec![7, 8, 9]),
            hint_points: Some(3),
            ..Default::default()
        })),
    );
}

#[test]
fn print_json_chat() {
    check(
        "print_json_chat",
        ServerPacket::PrintJSON(PrintJson {
            data: vec![JsonMessagePart::text("hello")],
            print_type: Some(PrintJsonType::Chat),
            slot: Some(2),
            message: Some("hello".into()),
            ..Default::default()
        }),
    );
}

#[test]
fn print_json_item_send() {
    check(
        "print_json_item_send",
        ServerPacket::PrintJSON(PrintJson {
            data: vec![
                JsonMessagePart::player_id(1),
                JsonMessagePart::text(" sent "),
                JsonMessagePart::item_id(77, 2, 1),
                JsonMessagePart::text(" to "),
                JsonMessagePart::player_id(2),
                JsonMessagePart::text(" ("),
                JsonMessagePart::location_id(1234, 1),
                JsonMessagePart::text(")"),
            ],
            print_type: Some(PrintJsonType::ItemSend),
            receiving: Some(2),
            item: Some(NetworkItem {
                item: 77,
                location: 1234,
                player: 1,
                flags: 1,
            }),
            ..Default::default()
        }),
    );
}

#[test]
fn non_ascii_text_is_not_escaped() {
    // Python uses ensure_ascii=False; escaping here would change every byte of
    // a message containing a non-ASCII slot name.
    check(
        "print_json_unicode",
        ServerPacket::PrintJSON(PrintJson {
            data: vec![JsonMessagePart::text("héllo ✓ 日本語")],
            print_type: Some(PrintJsonType::Chat),
            ..Default::default()
        }),
    );
}

#[test]
fn print_json_hint() {
    check(
        "print_json_hint",
        ServerPacket::PrintJSON(PrintJson {
            data: vec![
                JsonMessagePart::text("hint"),
                JsonMessagePart {
                    hint_status: Some(HintStatus::Priority),
                    ..JsonMessagePart::typed("hint_status", "30")
                },
            ],
            print_type: Some(PrintJsonType::Hint),
            receiving: Some(1),
            item: Some(NetworkItem {
                item: 5,
                location: 100,
                player: 2,
                flags: 1,
            }),
            found: Some(false),
            ..Default::default()
        }),
    );
}

#[test]
fn data_package() {
    check(
        "data_package",
        ServerPacket::DataPackage(DataPackage {
            data: DataPackageContents {
                games: BTreeMap::from([
                    (
                        "Archipelago".to_string(),
                        GameData {
                            item_name_to_id: BTreeMap::from([("Nothing".to_string(), 0)]),
                            location_name_to_id: BTreeMap::from([(
                                "Cheat Console".to_string(),
                                -1,
                            )]),
                            checksum: Some("aaa".into()),
                        },
                    ),
                    (
                        "Timespinner".to_string(),
                        GameData {
                            item_name_to_id: BTreeMap::from([
                                ("Blade".to_string(), 1),
                                ("Orb".to_string(), 2),
                            ]),
                            location_name_to_id: BTreeMap::from([("Chest".to_string(), 10)]),
                            checksum: Some("bbb".into()),
                        },
                    ),
                ]),
            },
        }),
    );
}

#[test]
fn invalid_packet() {
    check(
        "invalid_packet_cmd",
        ServerPacket::InvalidPacket(InvalidPacket {
            problem_type: "cmd".into(),
            original_cmd: None,
            text: "Unknown command Nonsense".into(),
        }),
    );
    check(
        "invalid_packet_args",
        ServerPacket::InvalidPacket(InvalidPacket {
            problem_type: "arguments".into(),
            original_cmd: Some("LocationChecks".into()),
            text: "locations must be a list of integers".into(),
        }),
    );
}

/// The echo replies. These are the strongest test in the file: they only match
/// if the request map is mutated in place, keeping `cmd` where the client put
/// it and carrying unknown keys through untouched.
#[test]
fn retrieved_echoes_the_request() {
    let mut req = Map::new();
    req.insert("cmd".into(), Value::String("Get".into()));
    req.insert("keys".into(), json!(["a", "b"]));
    req.insert("client_tag".into(), json!(7));

    check(
        "retrieved",
        ServerPacket::echo(req, "Retrieved", &[("keys", json!({"a": 1, "b": null}))]),
    );
}

#[test]
fn set_reply_appends_after_the_request_fields() {
    let mut req = Map::new();
    req.insert("cmd".into(), Value::String("Set".into()));
    req.insert("key".into(), Value::String("counter".into()));
    req.insert("want_reply".into(), json!(true));

    check(
        "set_reply",
        ServerPacket::echo(
            req,
            "SetReply",
            &[
                ("original_value", json!(1)),
                ("value", json!(2)),
                ("slot", json!(3)),
            ],
        ),
    );
}

#[test]
fn bounced_is_the_bounce_with_cmd_rewritten() {
    let mut req = Map::new();
    req.insert("cmd".into(), Value::String("Bounce".into()));
    req.insert("tags".into(), json!(["DeathLink"]));
    req.insert(
        "data".into(),
        json!({"time": 1700000000.5, "cause": "fell", "source": "Alice"}),
    );

    check("bounced", ServerPacket::echo(req, "Bounced", &[]));
}

#[test]
fn hint_values_carry_their_class_tag() {
    // Hint is only ever sent, never accepted, but it still has to serialize
    // with its tag and an integer status.
    let h = Hint {
        receiving_player: 1,
        finding_player: 2,
        location: 3,
        item: 4,
        found: false,
        entrance: String::new(),
        item_flags: 1,
        status: HintStatus::Priority,
    };
    let mut req = Map::new();
    req.insert("cmd".into(), Value::String("PrintJSON".into()));
    req.insert("data".into(), json!([{"text": "x"}]));
    req.insert("type".into(), Value::String("Hint".into()));
    req.insert("extra_hint".into(), serde_json::to_value(&h).unwrap());

    check("hint_value", ServerPacket::Echo(req));
}

#[test]
fn every_vector_is_exercised() {
    // A vector nobody checks is a test that silently stopped running.
    let cases: Vec<&str> = VECTORS
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|l| l.split_once('\t').map(|(n, _)| n))
        .collect();
    assert_eq!(cases.len(), 19, "vector count changed: {cases:?}");
}
